### ISSUE TITLE
Tutorial #1 - "Run project" failed

### ISSUE THREAD

**Issue by pducrot** [keiserlab/LUNA#38]
Hi, 
Running the tutorial #1 in Jupyter notebook failed with the following message:

```
proj_obj = luna.projects.LocalProject(**opts)
proj_obj.run()
```

```
[2022-10-05 10:12:45]    ERROR               jobs.py:99         Required structure doesn't exist
Traceback (most recent call last):
  File "/Users/pierre/anaconda3/envs/luna-env/lib/python3.7/urllib/request.py", line 1566, in ftp_open
    fw = self.connect_ftp(user, passwd, host, port, dirs, req.timeout)
  File "/Users/pierre/anaconda3/envs/luna-env/lib/python3.7/urllib/request.py", line 1588, in connect_ftp
    persistent=False)
  File "/Users/pierre/anaconda3/envs/luna-env/lib/python3.7/urllib/request.py", line 2408, in __init__
    self.init()
  File "/Users/pierre/anaconda3/envs/luna-env/lib/python3.7/urllib/request.py", line 2420, in init
    self.ftp.cwd(_target)
  File "/Users/pierre/anaconda3/envs/luna-env/lib/python3.7/ftplib.py", line 638, in cwd
    return self.voidcmd(cmd)
  File "/Users/pierre/anaconda3/envs/luna-env/lib/python3.7/ftplib.py", line 280, in voidcmd
    return self.voidresp()
  File "/Users/pierre/anaconda3/envs/luna-env/lib/python3.7/ftplib.py", line 253, in voidresp
    resp = self.getresp()
  File "/Users/pierre/anaconda3/envs/luna-env/lib/python3.7/ftplib.py", line 248, in getresp
    raise error_perm(resp)
ftplib.error_perm: 550 Can't change directory to pub/pdb/data/structures/divided/pdb/4: No such file or directory
```

**Comment by alexandrefassio** [comment]
Hi @pducrot,

I just fixed this bug. By mistake, the PDB file used in the tutorial was removed at some point. Now everything should work fine.

Update your repo version and try it out again. Lmk if you have any doubts or other issues.

bests

**Comment by pducrot** [comment]
It's now working, thanks.
