### ISSUE TITLE
Installation error on window

### ISSUE THREAD

**Issue by weiOasis1** [keiserlab/LUNA#43]
Hello,
I installed it according to the steps you gave,but when i use ### pip install luna, i get this error :

(luna-env) PS E:\论文\图神经网络\LUNA\LUNA-master> pip install luna
WARNING: Ignoring invalid distribution -tkinter-pymol (d:\anaconda3\envs\luna-env\dlls)
WARNING: Ignoring invalid distribution -tkinter-pymol (d:\anaconda3\envs\luna-env\dlls)
Collecting luna
  Using cached luna-0.12.2.tar.gz (1.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      D:\Anaconda3\envs\luna-env\lib\openbabel\__init__.py:15: UserWarning: "import openbabel" is deprecated, instead use "from openbabel import openbabel"
        warnings.warn('"import openbabel" is deprecated, instead use "from openbabel import openbabel"')
      'gbk' codec can't decode byte 0x98 in position 4512: illegal multibyte sequence
      Traceback (most recent call last):
        File "C:\Users\oasis\AppData\Local\Temp\pip-install-6gyd323a\luna_d2256ffdc9fa41c98de5ae4da1ca0758\luna\util\config.py", line 27, in __init__
          self.config.read(config_file)
        File "D:\Anaconda3\envs\luna-env\lib\configparser.py", line 696, in read
          self._read(fp, filename)
        File "D:\Anaconda3\envs\luna-env\lib\configparser.py", line 1014, in _read
          for lineno, line in enumerate(fp, start=1):
      UnicodeDecodeError: 'gbk' codec can't decode byte 0x98 in position 4512: illegal multibyte sequence
      Traceback (most recent call last):
        File "C:\Users\oasis\AppData\Local\Temp\pip-install-6gyd323a\luna_d2256ffdc9fa41c98de5ae4da1ca0758\luna\util\config.py", line 27, in __init__
          self.config.read(config_file)
        File "D:\Anaconda3\envs\luna-env\lib\configparser.py", line 696, in read
          self._read(fp, filename)
        File "D:\Anaconda3\envs\luna-env\lib\configparser.py", line 1014, in _read
          for lineno, line in enumerate(fp, start=1):
      UnicodeDecodeError: 'gbk' codec can't decode byte 0x98 in position 4512: illegal multibyte sequence

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\oasis\AppData\Local\Temp\pip-install-6gyd323a\luna_d2256ffdc9fa41c98de5ae4da1ca0758\setup.py", line 28, in <module>
          from luna.version import version
        File "C:\Users\oasis\AppData\Local\Temp\pip-install-6gyd323a\luna_d2256ffdc9fa41c98de5ae4da1ca0758\luna\__init__.py", line 2, in <module>
          from luna.projects import Project, LocalProject
        File "C:\Users\oasis\AppData\Local\Temp\pip-install-6gyd323a\luna_d2256ffdc9fa41c98de5ae4da1ca0758\luna\projects.py", line 16, in <module>
          from luna.config.params import ProjectParams
        File "C:\Users\oasis\AppData\Local\Temp\pip-install-6gyd323a\luna_d2256ffdc9fa41c98de5ae4da1ca0758\luna\config\params.py", line 7, in <module>
          from luna.mol.entry import *
        File "C:\Users\oasis\AppData\Local\Temp\pip-install-6gyd323a\luna_d2256ffdc9fa41c98de5ae4da1ca0758\luna\mol\entry.py", line 16, in <module>
          from luna.util.default_values import ACCEPTED_MOL_OBJ_TYPES, ENTRY_SEPARATOR, ARTIFACTS_LIST
        File "C:\Users\oasis\AppData\Local\Temp\pip-install-6gyd323a\luna_d2256ffdc9fa41c98de5ae4da1ca0758\luna\util\default_values.py", line 20, in <module>
          INTERACTION_CONFIG = DefaultInteractionConfig()
        File "C:\Users\oasis\AppData\Local\Temp\pip-install-6gyd323a\luna_d2256ffdc9fa41c98de5ae4da1ca0758\luna\interaction\config.py", line 80, in __init__
          config = InteractionConfig.from_config_file(default_config_file)
        File "C:\Users\oasis\AppData\Local\Temp\pip-install-6gyd323a\luna_d2256ffdc9fa41c98de5ae4da1ca0758\luna\interaction\config.py", line 46, in from_config_file
          params = Config(config_file)
        File "C:\Users\oasis\AppData\Local\Temp\pip-install-6gyd323a\luna_d2256ffdc9fa41c98de5ae4da1ca0758\luna\util\config.py", line 30, in __init__
          raise IOError('Configuration file %s not read.' % config_file)
      OSError: Configuration file C:\Users\oasis\AppData\Local\Temp\pip-install-6gyd323a\luna_d2256ffdc9fa41c98de5ae4da1ca0758\luna\interaction/config.cfg not read.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: Ignoring invalid distribution -tkinter-pymol (d:\anaconda3\envs\luna-env\dlls)
WARNING: Ignoring invalid distribution -tkinter-pymol (d:\anaconda3\envs\luna-env\dlls)
WARNING: Ignoring invalid distribution -tkinter-pymol (d:\anaconda3\envs\luna-env\dlls)

Many thanks

**Comment by alexandrefassio** [comment]
Hi @weiOasis1,

This error is related to text encoding. The errors specifically occur when reading a config file using configparser.ConfigParser. By default, ConfigParser.read() uses a platform-dependent encoding. So, this can be fixed if we set the encoding to 'utf-8'.

I forced LUNA to read a config file using your particular encoding, i.e., 'gbk', and was able to find the same issue as yours. By setting it to 'utf-8', the error disappeared.

I'll prepare a commit to fix this issue permanently, but meanwhile, if you prefer to fix it in advance you can download the LUNA source code and then update line # 27 from luna/util/config.py by adding the proper encoding. It should look like this:

```self.config.read(config_file, encoding='utf-8')```

Then you can run the setup.py to install LUNA as shown [here](https://luna-toolkit.readthedocs.io/en/latest/install.html#option-2-build-from-source).

Please, give it a try a let me know if it works. If you have any other issues also let me know.

bests

**Comment by mjke** [comment]
hi @weiOasis1 - was this able to fix your problem?

**Comment by alexandrefassio** [comment]
Feel free to reopen if you still need some help.
