### ISSUE TITLE
Import luna error

### ISSUE THREAD

**Issue by EvgeniyNam** [keiserlab/LUNA#47]
Hi!
I was trying luna package, but faced with a problem. I wanted to run this code:
`import matplotlib.pyplot as plt
import luna
import os
import time

from luna.mol.entry import MolEntry, MolFileEntry, ChainEntry

entry = MolFileEntry.from_mol_file(pdb_id="7JOZ", mol_id="CHEMBL113196", mol_file="CHEMBL113196_dock001.mol2",
                                    mol_obj_type='openbabel', is_multimol_file=False)

input_file = "./outputs/entries.txt"
entries = list(MolFileEntry.from_file(input_file, pdb_id="7JOZ", mol_file="CHEMBL113196_dock001.mol2", mol_obj_type="openbabel"))

for e in entries:
    print(e)
print()

entries[0].mol_obj.as_rdkit()`

And I got _OSError: File 'C:\Users\User\miniconda3\envs\luna-env\lib\site-packages\luna-0.13.1-py3.7.egg\luna\interaction\config.cfg' does not exist._

The full messege looks like this:

> C:\Users\User\miniconda3\envs\luna-env\python.exe C:\Users\User\Desktop\Study_projects\DDE\Luna\Luna-test.py 
C:\Users\User\miniconda3\envs\luna-env\lib\openbabel\__init__.py:14: UserWarning: "import openbabel" is deprecated, instead use "from openbabel import openbabel"
  warnings.warn('"import openbabel" is deprecated, instead use "from openbabel import openbabel"')
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Study_projects\DDE\Luna\Luna-test.py", line 2, in <module>
    import luna
  File "C:\Users\User\miniconda3\envs\luna-env\lib\site-packages\luna-0.13.1-py3.7.egg\luna\__init__.py", line 2, in <module>
    from luna.projects import Project, LocalProject
  File "C:\Users\User\miniconda3\envs\luna-env\lib\site-packages\luna-0.13.1-py3.7.egg\luna\projects.py", line 16, in <module>
    from luna.config.params import ProjectParams
  File "C:\Users\User\miniconda3\envs\luna-env\lib\site-packages\luna-0.13.1-py3.7.egg\luna\config\params.py", line 7, in <module>
    from luna.mol.entry import *
  File "C:\Users\User\miniconda3\envs\luna-env\lib\site-packages\luna-0.13.1-py3.7.egg\luna\mol\entry.py", line 17, in <module>
    from luna.util.default_values import (ACCEPTED_MOL_OBJ_TYPES, ENTRY_SEPARATOR,
  File "C:\Users\User\miniconda3\envs\luna-env\lib\site-packages\luna-0.13.1-py3.7.egg\luna\util\default_values.py", line 20, in <module>
    INTERACTION_CONFIG = DefaultInteractionConfig()
  File "C:\Users\User\miniconda3\envs\luna-env\lib\site-packages\luna-0.13.1-py3.7.egg\luna\interaction\config.py", line 98, in __init__
    config = InteractionConfig.from_config_file(default_config_file)
  File "C:\Users\User\miniconda3\envs\luna-env\lib\site-packages\luna-0.13.1-py3.7.egg\luna\interaction\config.py", line 54, in from_config_file
    raise OSError("File '%s' does not exist." % config_file)
OSError: File 'C:\Users\User\miniconda3\envs\luna-env\lib\site-packages\luna-0.13.1-py3.7.egg\luna\interaction\config.cfg' does not exist.

Process finished with exit code 1

Maybe you know what the problem is?

**Comment by EvgeniyNam** [comment]
Upd: It turned out that Windows blocked downloading the config file; I just had to manually install it in the desired directory
