### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by vedasoham** [keiserlab/LUNA#49]
(base) jrf@student45-OptiPlex-7000:~/JRF$ conda env create -f luna-env.yml --solver=libmamba

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/jrf/anaconda3/lib/python3.10/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
      File "/home/jrf/anaconda3/lib/python3.10/site-packages/conda_env/cli/main.py", line 56, in do_call
        exit_code = getattr(module, func_name)(arguments, parser)
      File "/home/jrf/anaconda3/lib/python3.10/site-packages/conda/notices/core.py", line 124, in wrapper
        return func(*args, **kwargs)
      File "/home/jrf/anaconda3/lib/python3.10/site-packages/conda_env/cli/main_create.py", line 105, in execute
        spec = specs.detect(
      File "/home/jrf/anaconda3/lib/python3.10/site-packages/conda_env/specs/__init__.py", line 72, in detect
        if spec.can_handle():
      File "/home/jrf/anaconda3/lib/python3.10/site-packages/conda_env/specs/yaml_file.py", line 19, in can_handle
        self._environment = env.from_file(self.filename)
      File "/home/jrf/anaconda3/lib/python3.10/site-packages/conda_env/env.py", line 191, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/home/jrf/anaconda3/lib/python3.10/site-packages/conda_env/env.py", line 158, in from_yaml
        data = yaml_safe_load(yamlstr)
      File "/home/jrf/anaconda3/lib/python3.10/site-packages/conda/common/serialize.py", line 53, in yaml_safe_load
        return _yaml_safe().load(string)
      File "/home/jrf/anaconda3/lib/python3.10/site-packages/ruamel/yaml/main.py", line 426, in load
        return constructor.get_single_data()
      File "/home/jrf/anaconda3/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 111, in get_single_data
        node = self.composer.get_single_node()
      File "/home/jrf/anaconda3/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 70, in get_single_node
        document = self.compose_document()
      File "/home/jrf/anaconda3/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 95, in compose_document
        self.parser.get_event()
      File "/home/jrf/anaconda3/lib/python3.10/site-packages/ruamel/yaml/parser.py", line 159, in get_event
        self.current_event = self.state()
      File "/home/jrf/anaconda3/lib/python3.10/site-packages/ruamel/yaml/parser.py", line 243, in parse_document_end
        token = self.scanner.peek_token()
      File "/home/jrf/anaconda3/lib/python3.10/site-packages/ruamel/yaml/scanner.py", line 180, in peek_token
        self.fetch_more_tokens()
      File "/home/jrf/anaconda3/lib/python3.10/site-packages/ruamel/yaml/scanner.py", line 276, in fetch_more_tokens
        return self.fetch_value()
      File "/home/jrf/anaconda3/lib/python3.10/site-packages/ruamel/yaml/scanner.py", line 626, in fetch_value
        raise ScannerError(
    ruamel.yaml.scanner.ScannerError: mapping values are not allowed here
      in "<unicode string>", line 203, column 75:
         ... age-responsive" style="word-wrap: break-word;">
                                             ^ (line: 203)

`$ /home/jrf/anaconda3/bin/conda-env create -f luna-env.yml --solver=libmamba`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/jrf/anaconda3/bin/conda
             CONDA_PREFIX=/home/jrf/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/jrf/anaconda3/bin/python
               CONDA_ROOT=/home/jrf/anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
               LD_PRELOAD=<not set>
                     PATH=/home/jrf/anaconda3/bin:/home/jrf/anaconda3/condabin:/usr/bin:/usr/loc
                          al/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/cuda/b
                          in
               PYTHONPATH=/home/jrf/MGLTools/MGLToolsPckgs/:
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=2

     active environment : base
    active env location : /home/jrf/anaconda3
            shell level : 1
       user config file : /home/jrf/.condarc
 populated config files : /home/jrf/.condarc
          conda version : 23.9.0
    conda-build version : 3.27.0
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.31=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /home/jrf/anaconda3  (writable)
      conda av data dir : /home/jrf/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          http://conda.lsst.codes/stack/0.12.1/linux-64
                          http://conda.lsst.codes/stack/0.12.1/noarch
          package cache : /home/jrf/anaconda3/pkgs
                          /home/jrf/.conda/pkgs
       envs directories : /home/jrf/anaconda3/envs
                          /home/jrf/.conda/envs
               platform : linux-64
             user-agent : conda/23.9.0 requests/2.31.0 CPython/3.10.12 Linux/5.15.0-94-generic ubuntu/20.04.6 glibc/2.31 solver/libmamba conda-libmamba-solver/23.9.1 libmambapy/1.5.1 aau/0.4.2 c/2F8StzCnOt5Dbz8FM14fsQ s/EYBufKOmXoXL2A-QmVvJ6g e/nCgJbp6EHSmmqbDGVG5RUA
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: N

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false

**Comment by alexandrefassio** [comment]
Hi @vedasoham 

I've updated LUNA codebase to 0.14.0 and removed dependency on legacy code. You should be able to install LUNA with conda successfully now.

Let me know if you have any issues. In that case, feel free to re-open this issue.

bests
