### ISSUE TITLE
Running the Calculate protein-ligand interactions command on windows gives an error

### ISSUE THREAD

**Issue by neo010010** [keiserlab/LUNA#53]
Hello, author.
I am encountering the following error while running the instructions for calculating protein-ligand interactions on windows platform:

(luna-env) C:\Users\abc\Desktop\AIDD\Code\LUNA>python luna/run.py -p example/inputs/protein.pdb -l example/inputs/ligands.mol2 -e example/inputs/entries.txt -w dopamine_results
D:\Anaconda\envs\luna-env\lib\openbabel\__init__.py:14: UserWarning: "import openbabel" is deprecated, instead use "from openbabel import openbabel"
  warnings.warn('"import openbabel" is deprecated, instead use "from openbabel import openbabel"')
Module 'simplejson' imported.
Module 'simplejson' imported.

▨ Creating a new LUNA project: 'dopamine_results'...

D:\Anaconda\envs\luna-env\lib\site-packages\luna\projects.py:349: LUNAWarning: Logging mode was set ON. Logging information will be saved from now on.
  self.logging_enabled = logging_enabled
[2024-09-15 17:08:46]    INFO            projects.py:590        LUNA version: 0.13.1.
[2024-09-15 17:08:46]    WARNING         projects.py:590        It was trying to create an invalid number of processes (-1). Therefore, the number of processes 'nproc' was set to its m
aximum accepted capacity (8 - 1 = 7).
[2024-09-15 17:08:46]    INFO            projects.py:590        Verbosity set to: 3 (INFO).
[2024-09-15 17:08:46]    INFO            projects.py:590        Preparing project directory 'dopamine_results'.
[2024-09-15 17:08:46]    WARNING         projects.py:590        The provided PDB path 'None' is not valid or does not exist. Therefore, PDBs will be saved at the working path: dopamine
_results/pdbs/
[2024-09-15 17:08:46]    INFO                file.py:200        The directory 'dopamine_results' already exists, but it will not be cleared.
[2024-09-15 17:08:46]    INFO                file.py:200        The directory 'dopamine_results/chunks' already exists, but it will not be cleared.
[2024-09-15 17:08:46]    INFO                file.py:200        The directory 'dopamine_results/configs' already exists, but it will not be cleared.
[2024-09-15 17:08:46]    INFO                file.py:200        The directory 'dopamine_results/logs' already exists, but it will not be cleared.
[2024-09-15 17:08:46]    INFO                file.py:200        The directory 'dopamine_results/pdbs' already exists, but it will not be cleared.
[2024-09-15 17:08:46]    INFO                file.py:200        The directory 'dopamine_results/results/interactions' already exists, but it will not be cleared.
[2024-09-15 17:08:46]    INFO                file.py:200        The directory 'dopamine_results/results/fingerprints' already exists, but it will not be cleared.
[2024-09-15 17:08:46]    INFO                file.py:200        The directory 'dopamine_results/results/pse' already exists, but it will not be cleared.
[2024-09-15 17:08:46]    INFO                file.py:200        The directory 'dopamine_results/results' already exists, but it will not be cleared.
[2024-09-15 17:08:46]    INFO                file.py:200        The directory 'dopamine_results/tmp' already exists, but it will not be cleared.
[2024-09-15 17:08:46]    INFO            projects.py:590        Project directory 'dopamine_results' created successfully.
[2024-09-15 17:08:46]    INFO            projects.py:590        Logging file 'dopamine_results/logs/project.log' initialized successfully.
[2024-09-15 17:08:46]    INFO            projects.py:590        The remotion of duplicate entries was finished. 0 entrie(s) were removed.
[2024-09-15 17:08:46]    INFO            projects.py:590        It will verify the existence of PDB files and download them as necessary.
[2024-09-15 17:08:46]    INFO            projects.py:706        0 PDB file(s) found at 'dopamine_results/pdbs/' from a total of 1 PDB(s). So, 1 PDB(s) need to be downloaded.
Traceback (most recent call last):
  File "luna/run.py", line 402, in <module>
    main()
  File "luna/run.py", line 324, in main
    pli_obj.run()
  File "D:\Anaconda\envs\luna-env\lib\site-packages\luna\projects.py", line 953, in run
    self()
  File "D:\Anaconda\envs\luna-env\lib\site-packages\luna\projects.py", line 1323, in __call__
    self.verify_pdb_files_existence()
TypeError: can't pickle _thread.lock objects

(luna-env) C:\Users\abc\Desktop\AIDD\Code\LUNA>D:\Anaconda\envs\luna-env\lib\openbabel\__init__.py:14: UserWarning: "import openbabel" is deprecated, instead use "from openbabel import
 openbabel"
  warnings.warn('"import openbabel" is deprecated, instead use "from openbabel import openbabel"')
Module 'simplejson' imported.
Module 'simplejson' imported.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Anaconda\envs\luna-env\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\Anaconda\envs\luna-env\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

What should I do to solve this problem?
Thanks!

**Comment by neo010010** [comment]
I tried adding --nproc 1 to the end of the command, but I still get the error.

(luna-env) C:\Users\abc\Desktop\AIDD\Code\LUNA>python luna/run.py -p example/inputs/protein.pdb -l example/inputs/ligands.mol2 -e example/inputs/entries.txt -w dopamine_results --nproc
 1
D:\Anaconda\envs\luna-env\lib\openbabel\__init__.py:14: UserWarning: "import openbabel" is deprecated, instead use "from openbabel import openbabel"
  warnings.warn('"import openbabel" is deprecated, instead use "from openbabel import openbabel"')                                                  
Module 'simplejson' imported.
Module 'simplejson' imported.

▨ Creating a new LUNA project: 'dopamine_results'...

D:\Anaconda\envs\luna-env\lib\site-packages\luna\projects.py:349: LUNAWarning: Logging mode was set ON. Logging information will be saved from now on.
  self.logging_enabled = logging_enabled
[2024-09-15 17:18:49]    INFO            projects.py:590        LUNA version: 0.13.1.
[2024-09-15 17:18:49]    INFO            projects.py:590        Verbosity set to: 3 (INFO).
[2024-09-15 17:18:49]    INFO            projects.py:590        Preparing project directory 'dopamine_results'.
[2024-09-15 17:18:49]    WARNING         projects.py:590        The provided PDB path 'None' is not valid or does not exist. Therefore, PDBs will be saved at the working path: dopamine
_results/pdbs/
[2024-09-15 17:18:49]    INFO                file.py:200        The directory 'dopamine_results' already exists, but it will not be cleared.
[2024-09-15 17:18:49]    INFO                file.py:200        The directory 'dopamine_results/chunks' already exists, but it will not be cleared.
[2024-09-15 17:18:49]    INFO                file.py:200        The directory 'dopamine_results/configs' already exists, but it will not be cleared.
[2024-09-15 17:18:49]    INFO                file.py:200        The directory 'dopamine_results/logs' already exists, but it will not be cleared.
[2024-09-15 17:18:49]    INFO                file.py:200        The directory 'dopamine_results/pdbs' already exists, but it will not be cleared.
[2024-09-15 17:18:49]    INFO                file.py:200        The directory 'dopamine_results/results/interactions' already exists, but it will not be cleared.
[2024-09-15 17:18:49]    INFO                file.py:200        The directory 'dopamine_results/results/fingerprints' already exists, but it will not be cleared.
[2024-09-15 17:18:49]    INFO                file.py:200        The directory 'dopamine_results/results/pse' already exists, but it will not be cleared.
[2024-09-15 17:18:49]    INFO                file.py:200        The directory 'dopamine_results/results' already exists, but it will not be cleared.
[2024-09-15 17:18:49]    INFO                file.py:200        The directory 'dopamine_results/tmp' already exists, but it will not be cleared.
[2024-09-15 17:18:49]    INFO            projects.py:590        Project directory 'dopamine_results' created successfully.
[2024-09-15 17:18:49]    INFO            projects.py:590        Logging file 'dopamine_results/logs/project.log' initialized successfully.
[2024-09-15 17:18:49]    INFO            projects.py:590        The remotion of duplicate entries was finished. 0 entrie(s) were removed.
[2024-09-15 17:18:49]    INFO            projects.py:590        It will verify the existence of PDB files and download them as necessary.
[2024-09-15 17:18:49]    INFO            projects.py:706        0 PDB file(s) found at 'dopamine_results/pdbs/' from a total of 1 PDB(s). So, 1 PDB(s) need to be downloaded.
[2024-09-15 17:18:49]    PROGRESS                               0% [                                                  ] 0/1 [Avg: 0.00s/task; Errors: 0] - Download PDBs.[2024-09-15 17:
18:50]    ERROR               jobs.py:105        Required structure doesn't exist
Traceback (most recent call last):
  File "D:\Anaconda\envs\luna-env\lib\urllib\request.py", line 1535, in ftp_open
    fw = self.connect_ftp(user, passwd, host, port, dirs, req.timeout)
  File "D:\Anaconda\envs\luna-env\lib\urllib\request.py", line 1557, in connect_ftp
    persistent=False)
  File "D:\Anaconda\envs\luna-env\lib\urllib\request.py", line 2377, in __init__
    self.init()
  File "D:\Anaconda\envs\luna-env\lib\urllib\request.py", line 2389, in init
    self.ftp.cwd(_target)
  File "D:\Anaconda\envs\luna-env\lib\ftplib.py", line 631, in cwd
    return self.voidcmd(cmd)
  File "D:\Anaconda\envs\luna-env\lib\ftplib.py", line 278, in voidcmd
    return self.voidresp()
  File "D:\Anaconda\envs\luna-env\lib\ftplib.py", line 251, in voidresp
    resp = self.getresp()
  File "D:\Anaconda\envs\luna-env\lib\ftplib.py", line 246, in getresp
    raise error_perm(resp)
ftplib.error_perm: 550 Can't change directory to pub/pdb/data/structures/divided/pdb/xa/pdbexample/inputs: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\luna-env\lib\site-packages\luna\MyBio\PDB\PDBList.py", line 286, in retrieve_pdb_file
    _urlretrieve(url, filename)
  File "D:\Anaconda\envs\luna-env\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "D:\Anaconda\envs\luna-env\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Anaconda\envs\luna-env\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "D:\Anaconda\envs\luna-env\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "D:\Anaconda\envs\luna-env\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "D:\Anaconda\envs\luna-env\lib\urllib\request.py", line 1553, in ftp_open
    raise exc.with_traceback(sys.exc_info()[2])
  File "D:\Anaconda\envs\luna-env\lib\urllib\request.py", line 1535, in ftp_open
    fw = self.connect_ftp(user, passwd, host, port, dirs, req.timeout)
  File "D:\Anaconda\envs\luna-env\lib\urllib\request.py", line 1557, in connect_ftp
    persistent=False)
  File "D:\Anaconda\envs\luna-env\lib\urllib\request.py", line 2377, in __init__
    self.init()
  File "D:\Anaconda\envs\luna-env\lib\urllib\request.py", line 2389, in init
    self.ftp.cwd(_target)
  File "D:\Anaconda\envs\luna-env\lib\ftplib.py", line 631, in cwd
    return self.voidcmd(cmd)
  File "D:\Anaconda\envs\luna-env\lib\ftplib.py", line 278, in voidcmd
    return self.voidresp()
  File "D:\Anaconda\envs\luna-env\lib\ftplib.py", line 251, in voidresp
    resp = self.getresp()
  File "D:\Anaconda\envs\luna-env\lib\ftplib.py", line 246, in getresp
    raise error_perm(resp)
urllib.error.URLError: <urlopen error ftp error: error_perm("550 Can't change directory to pub/pdb/data/structures/divided/pdb/xa/pdbexample/inputs: No such file or directory")>       

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\luna-env\lib\site-packages\luna\util\jobs.py", line 99, in _exec_func
    output = func(*data)
  File "D:\Anaconda\envs\luna-env\lib\site-packages\luna\MyBio\util.py", line 68, in download_pdb
    file_format="pdb", overwrite=overwrite)
  File "D:\Anaconda\envs\luna-env\lib\site-packages\luna\MyBio\PDB\PDBList.py", line 288, in retrieve_pdb_file
    raise IOError("Required structure doesn't exist")
OSError: Required structure doesn't exist
[2024-09-15 17:18:50]    PROGRESS                               100% [■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■] 1/1 [Avg: 1.25s/task; Errors: 1] - Download PDBs.
[2024-09-15 17:18:50]    WARNING         projects.py:590        Number of PDBs with errors: 1. Check the log file to see the complete list of PDBs that failed.
[2024-09-15 17:18:50]    INFO            projects.py:590        Entries processing will start. Number of entries to be processed is: 5.
[2024-09-15 17:18:50]    INFO            projects.py:590        The number of processes was set to: 1.
[2024-09-15 17:18:50]    ERROR               jobs.py:105        [Errno 2] No such file or directory: 'dopamine_results/pdbs//example/inputs/protein.pdb.pdb'
Traceback (most recent call last):
  File "D:\Anaconda\envs\luna-env\lib\site-packages\luna\util\jobs.py", line 102, in _exec_func
    output = func(data)
  File "D:\Anaconda\envs\luna-env\lib\site-packages\luna\projects.py", line 1149, in _process_entry
    pdb_parser, structure, ligand = self._parse_complex(entry)
  File "D:\Anaconda\envs\luna-env\lib\site-packages\luna\projects.py", line 760, in _parse_complex
    structure = pdb_parser.get_structure(entry.pdb_id, pdb_file)
  File "D:\Anaconda\envs\luna-env\lib\site-packages\luna\MyBio\PDB\PDBParser.py", line 151, in get_structure
    with as_handle(file, mode='rU') as handle:
  File "D:\Anaconda\envs\luna-env\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "D:\Anaconda\envs\luna-env\lib\site-packages\Bio\File.py", line 101, in as_handle
    with open(handleish, mode, **kwargs) as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'dopamine_results/pdbs//example/inputs/protein.pdb.pdb'
[2024-09-15 17:18:50]    PROGRESS                               20% [■■■■■■■■■■                                        ] 1/5 [Avg: 0.00s/task; Errors: 1] - Entries processing.[2024-09-
15 17:18:50]    ERROR               jobs.py:105        [Errno 2] No such file or directory: 'dopamine_results/pdbs//example/inputs/protein.pdb.pdb'
Traceback (most recent call last):
  File "D:\Anaconda\envs\luna-env\lib\site-packages\luna\util\jobs.py", line 102, in _exec_func
    output = func(data)
  File "D:\Anaconda\envs\luna-env\lib\site-packages\luna\projects.py", line 1149, in _process_entry
    pdb_parser, structure, ligand = self._parse_complex(entry)
  File "D:\Anaconda\envs\luna-env\lib\site-packages\luna\projects.py", line 760, in _parse_complex
    structure = pdb_parser.get_structure(entry.pdb_id, pdb_file)
  File "D:\Anaconda\envs\luna-env\lib\site-packages\luna\MyBio\PDB\PDBParser.py", line 151, in get_structure
    with as_handle(file, mode='rU') as handle:
  File "D:\Anaconda\envs\luna-env\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "D:\Anaconda\envs\luna-env\lib\site-packages\Bio\File.py", line 101, in as_handle
    with open(handleish, mode, **kwargs) as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'dopamine_results/pdbs//example/inputs/protein.pdb.pdb'
[2024-09-15 17:18:50]    ERROR               jobs.py:105        [Errno 2] No such file or directory: 'dopamine_results/pdbs//example/inputs/protein.pdb.pdb'
Traceback (most recent call last):
  File "D:\Anaconda\envs\luna-env\lib\site-packages\luna\util\jobs.py", line 102, in _exec_func
    output = func(data)
  File "D:\Anaconda\envs\luna-env\lib\site-packages\luna\projects.py", line 1149, in _process_entry
    pdb_parser, structure, ligand = self._parse_complex(entry)
  File "D:\Anaconda\envs\luna-env\lib\site-packages\luna\projects.py", line 760, in _parse_complex
    structure = pdb_parser.get_structure(entry.pdb_id, pdb_file)
  File "D:\Anaconda\envs\luna-env\lib\site-packages\luna\MyBio\PDB\PDBParser.py", line 151, in get_structure
    with as_handle(file, mode='rU') as handle:
  File "D:\Anaconda\envs\luna-env\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "D:\Anaconda\envs\luna-env\lib\site-packages\Bio\File.py", line 101, in as_handle
    with open(handleish, mode, **kwargs) as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'dopamine_results/pdbs//example/inputs/protein.pdb.pdb'
[2024-09-15 17:18:51]    PROGRESS                               60% [■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                    ] 3/5 [Avg: 0.00s/task; Errors: 3] - Entries processing.[2024-09-
15 17:18:51]    ERROR               jobs.py:105        [Errno 2] No such file or directory: 'dopamine_results/pdbs//example/inputs/protein.pdb.pdb'
Traceback (most recent call last):
  File "D:\Anaconda\envs\luna-env\lib\site-packages\luna\util\jobs.py", line 102, in _exec_func
    output = func(data)
  File "D:\Anaconda\envs\luna-env\lib\site-packages\luna\projects.py", line 1149, in _process_entry
    pdb_parser, structure, ligand = self._parse_complex(entry)
  File "D:\Anaconda\envs\luna-env\lib\site-packages\luna\projects.py", line 760, in _parse_complex
    structure = pdb_parser.get_structure(entry.pdb_id, pdb_file)
  File "D:\Anaconda\envs\luna-env\lib\site-packages\luna\MyBio\PDB\PDBParser.py", line 151, in get_structure
    with as_handle(file, mode='rU') as handle:
  File "D:\Anaconda\envs\luna-env\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "D:\Anaconda\envs\luna-env\lib\site-packages\Bio\File.py", line 101, in as_handle
    with open(handleish, mode, **kwargs) as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'dopamine_results/pdbs//example/inputs/protein.pdb.pdb'
[2024-09-15 17:18:51]    ERROR               jobs.py:105        [Errno 2] No such file or directory: 'dopamine_results/pdbs//example/inputs/protein.pdb.pdb'
Traceback (most recent call last):
  File "D:\Anaconda\envs\luna-env\lib\site-packages\luna\util\jobs.py", line 102, in _exec_func
    output = func(data)
[2024-09-15 17:18:51]    PROGRESS                               100% [■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■] 5/5 [Avg: 0.00s/task; Errors: 5] - Entries processing.        
[2024-09-15 17:18:51]    CRITICAL        projects.py:590        Entries processing failed.
[2024-09-15 17:18:51]    INFO            projects.py:590        Project creation completed!!!
[2024-09-15 17:18:51]    INFO            projects.py:590        Total processing time: 1.70s.
[2024-09-15 17:18:51]    INFO            projects.py:590        Results were saved at dopamine_results.
[2024-09-15 17:18:51]    INFO            projects.py:590        You can reload your project from dopamine_results/project_v0.13.1.pkl.gz.
